feat(updatederivedcfg): Added UpdateDerivedCfg
ARKlab/Artesian.SDK pull request #94
Opened 2024-12-19 17:27 UTC by jacopocinaark

Added the UpdateDerivedCfg

ref: #18962

2024-12-24 08:56 UTC, AndreaCuneo requested changes
There is another PR on the same topic: #67 . Please consolidate changes and comments.

This PR lacks changes to the https://github.com/ARKlab/Artesian.SDK/blob/master/Artesian/Artesian.SDK/Factory/MarketData.cs object. In the MarketData object, client-side validations are expected.

mkd.UpdateDerivedConfig(...)
   * validate that is a derived marketdata
   * validate that new config is the same type, provide multiple overloads for each type
   * ???

Discuss client-side validation with @arkcecchi

2025-01-07 13:05 UTC, AndreaCuneo requested changes

2025-01-07 16:13 UTC, AndreaCuneo requested changes

2025-01-07 16:13 UTC, AndreaCuneo commented on Artesian/Artesian.SDK/Factory/IMarketData.cs
> +        Task UpdateDerivedConfiguration(DerivedCfgMuv derivedCfg, bool force, CancellationToken ctk = default);
I'm sure Backend defines 'force' with default 'false'.

That should be here too.

Could ve best to have 2 overloads, so in case force is not needed but ctk is (should) the ctk can be passed without having to define the force parameter.

Update(cfg,ctk) => Update(cfg,false,ctk);
Update(cfg,force,ctk)

2025-01-07 16:13 UTC, AndreaCuneo commented on Artesian/Artesian.SDK/Factory/MarketData.cs
> +        public async Task UpdateDerivedConfiguration(DerivedCfgMuv derivedCfg, bool force, CancellationToken ctk = default)
force is optional, defaults to false in backend.

keep the same here.

use Overloads for DX over ctk propagation.

2025-01-07 16:13 UTC, AndreaCuneo commented on Artesian/Artesian.SDK/Service/MarketData/IMarketDataService.cs
> +        Task<MarketDataEntity.Output> UpdateDerivedConfigurationAsync(int marketDataId, DerivedCfgBase derivedCfg, bool force, CancellationToken ctk = default);
force optional

2025-01-08 08:02 UTC, AndreaCuneo approved these changes

2025-01-08 09:52 UTC, arkcecchi approved these changes

2025-01-08 09:52 UTC, merged